### ISSUE TITLE
Switch to Yarn

### ISSUE THREAD

**Issue by dtribble** [Agoric/cosmic-workspace#8]
Yarn replaced NPM usage such that it tries to have a single version of each library rather than each package having copies of it's own libraries. We would rather have a single consistent version of each library. Fundamentally, cosmic-swingset and ERTP should not be getting their own (possibly different) versions of SwingSet.

Tasks include

- [ ] Replace doRun.js with yarn

**Comment by michaelfig** [comment]
I fixed this by using the `lerna` package, which manages subpackages much like Yarn, but does not enforce a specific package manager.  README remains the same, and a single consistent version of each library is used.

Reopen if you find this inadequate.
